language: python
python:
- '2.7'
install:
- sudo wget -nv http://files.vagrantup.com/packages/7e400d00a3c5a0fdf2809c8b5001a035415a607b/vagrant_1.2.2_x86_64.deb
- sudo dpkg -i vagrant_1.2.2_x86_64.deb
- pip install -r ./ci/requirements.txt
- python setup.py develop
before_script:
- nepho cloudlet install nepho-example
script:
- flake8 .
- nosetests -v
notifications:
  hipchat:
    rooms:
      secure: frn3Xhgyrn8vutgNJeiTLauMalF9lqVhXxAT/0ff5OKYfzEWM6PgnDSB8VFnNxi09IfSQaXGgZJrCQgdEsbrMWAxaW9Ycxv2rZ9Av/dM7THz/HjsoipBXnXkcErBTOH9bBJU/ICDHzP2oqmfEojBH/zFIeMqpaySUPVgC4HDWEs=
